apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    module: import
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
        - name: {{ .Release.Name }}
          image: {{ if .Values.dev }} {{ .Release.Name }} {{ else }} wdias/{{ .Release.Name }} {{ end }}
          imagePullPolicy: {{ if .Values.dev }} Never {{ else }} Always {{ end }}
          volumeMounts:
            - mountPath: /data
              name: data-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /public/hc
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /public/hc
          #     port: http
          resources:
            #limits:
              #memory: 256Mi
              #cpu: 200m
            #requests:
              #memory: 128Mi
              #cpu: 150m
        - name: worker
          image: {{ if .Values.dev }} {{ .Release.Name }} {{ else }} wdias/{{ .Release.Name }} {{ end }}
          imagePullPolicy: {{ if .Values.dev }} Never {{ else }} Always {{ end }}
          volumeMounts:
            - mountPath: /data
              name: data-volume
          env:
            - name: APPNAME
              value: "worker"
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 30
            preference:
              matchExpressions:
              - key: module
                operator: In
                values:
                - grid
