# Redis Database Configurations

password: wdias123

cluster:
  enabled: false

master:
  persistence:
    enabled: false
  service:
    type: NodePort
  ## Redis Master Node selectors and tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
  ##
  # nodeSelector: {"beta.kubernetes.io/arch": "amd64"}
  # tolerations: []
  ## Redis Master pod/node affinity/anti-affinity
  ##
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 20
        preference:
          matchExpressions:
          - key: module
            operator: In
            values:
            - core
      - weight: 10
        preference:
          matchExpressions:
          - key: module
            operator: NotIn
            values:
            - scalar
            - grid
            - test

slave:
  ## Redis slave selectors and tolerations for pod assignment
  # nodeSelector: {"beta.kubernetes.io/arch": "amd64"}
  # tolerations: []
  ## Redis Slave pod/node affinity/anti-affinity
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 20
        preference:
          matchExpressions:
          - key: module
            operator: In
            values:
            - core
      - weight: 10
        preference:
          matchExpressions:
          - key: module
            operator: NotIn
            values:
            - scalar
            - grid
            - test
