apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    module: import
spec:
  # type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
