# Default values for import-json-raw.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dev: false
replicaCount: 1

redisHost: 'adapter-redis-master.default.svc.cluster.local'
redisPort: 6379
redisDB: 0
redisPassword: wdias123