mysqlRootPassword: root123
mysqlUser: wdias
mysqlPassword: wdias123
mysqlDatabase: metadata

persistence:
  enabled: false
  size: 500Mi

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 150m
