args:
  # - --tls-cert-file=default/noondv.com-tls
  # - --tls-private-key-file=default/noondv.com-tls
  - --kubelet-insecure-tls

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 20
      preference:
        matchExpressions:
        - key: module
          operator: In
          values:
          - test
    - weight: 10
      preference:
        matchExpressions:
        - key: module
          operator: NotIn
          values:
          - grid
          - scalar
