mysqlRootPassword: root123
mysqlUser: wdias
mysqlPassword: wdias123
mysqlDatabase: extension

persistence:
  enabled: false
  size: 1Gi

resources:
  limits:
    #memory: 256Mi
    #cpu: 200m
  requests:
    memory: 256Mi
    cpu: 100m
