mongodbRootPassword: root123
mongodbUsername: wdias
mongodbPassword: wdias123
mongodbDatabase: query

persistence:
  enabled: false
  size: 1Gi

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 256Mi
    cpu: 150m
