mongodbRootPassword: root123
mongodbUsername: wdias
mongodbPassword: wdias123
mongodbDatabase: query

persistence:
  enabled: false
  size: 5Gi

resources:
  limits:
    #memory: 256Mi
    #cpu: 200m
  requests:
    memory: 256Mi
    cpu: 150m

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 15
      preference:
        matchExpressions:
        - key: module
          operator: In
          values:
          - core
    - weight: 10
      preference:
        matchExpressions:
        - key: module
          operator: NotIn
          values:
          - scalar
          - grid
          - test
# Define separate affinity for arbiter pod
affinityArbiter: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
